apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 82
      targetPort: 82
      nodePort: 30100
  selector:
    name: result-app-pod
    app: demo-voting-app

